#ifndef OTIC_CONFIG_H
#define OTIC_CONFIG_H

#define OTIC_VERSION_MAJOR 1
#define OTIC_VERSION_MINOR 0
#define OTIC_VERSION_PATCH 0

#define OTIC_BIG_ENDIAN_SYS 0
#define OTIC_HAS_ENDIAN_H   1

#define OTIC_STATS 1
#define OTIC_PACK_NO_COMPRESSION 0
#define OTIC_PACK_INLINE_ALL_STATIC 1
#define OTIC_UNPACK_INLINE_ALL_STATIC 1

#define OTIC_PACK_BUCKET_SIZE 3276800

#endif //OTIC_CONFIG_H
