# Kickstart container config file - see https://gitub.com/infracamp/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "infracamp/kickstart-flavor-base"
command:
  build:
    - "sudo apt-get update"
    - "sudo apt-get install -y pkg-config libzstd1-dev build-essential php7.2-dom php7.2-mbstring php-dev cmake"
  init:

  make:
    - "if [ -d `pwd`/kbuild ]; then rm -rf `pwd`/kbuild/*; else mkdir kbuild; fi"
    - "cmake . -Bkbuild -DCMAKE_BUILD_TYPE=Release"
    - "make -C kbuild"
    #- "sudo make install -C kbuild"
    - "sudo ldconfig"
    - "cp /opt/bindings/php7/lib/libotic_php.so /opt/dist/"
    - "cp /opt/bin/otic /opt/dist/otic"

  test:
    - "echo hallo"
#    - "cd kbuild && ctest"
#    - "ls"

  run:
  dev:
    - "echo 'I am executed in dev mode'"
