# Kickstart container config file - see https://gitub.com/infracamp/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "infracamp/kickstart-flavor-base"
command:
  build:
    - "sudo apt-get update"
    - "sudo apt-get install -y pkg-config libzstd1-dev build-essential php7.2-dom php7.2-mbstring php-dev cmake"
    - "sudo rm -rf deps/Unity"
    - "[[ -d 'deps/Unity' ]] || git clone https://github.com/ThrowTheSwitch/Unity.git deps/Unity"
    - "sudo rm -rf build"
    - "sudo rm -rf deps/Unity/build"
    - "mkdir -p deps/Unity/build"
    - "cmake deps/Unity -Bdeps/Unity/build -DCMAKE_BUILD_TYPE=Release && sudo make -C deps/Unity/build install"

  init:

  make:
    - "sudo rm -rf build"
    - "mkdir -p build && cmake . -Bbuild -DCMAKE_BUILD_TYPE=Release && make -C build"
    - "sudo ldconfig"

  test:
    - "make test -C build"

  run:
  dev:
    - "echo 'I am executed in dev mode'"
