# Kickstart container config file - see https://gitub.com/infracamp/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "infracamp/kickstart-flavor-gaia:testing"
command:
  build:
    - "sudo apt-get update"
    - "sudo apt-get install -y pkg-config"
    - "sudo apt-get install -y libzstd1-dev build-essential"
    - "sudo apt-get install -y python3 python3-dev"
    - "sudo apt-get install -y python3-pip"
    - "sudo apt-get install -y php7.2-dom php7.2-mbstring"
    - "sudo apt-get install -y php-dev"
    - "sudo apt-get install -y afl"
    - "composer update"
    - "python3 -m pip install cffi hypothesis pytest zstandard"
    - "kick build-c-lib"

  build-c-lib:
    - "cd /opt/src && make"
    - "cd /opt/examples && make"
    - "cd /opt/phpsrc/otic && phpize --clean && phpize && ./configure && NO_INTERACTION=1 make"
    - "echo 'extension=/opt/phpsrc/otic/modules/otic.so' | sudo tee /etc/php/7.2/mods-available/otic.ini"
    - "sudo phpenmod otic"

  test:
    - "cd /opt/src && make"
    - "cd /opt/examples && make"
    - "cd /opt/src/oticreference/ && python3 build_cffi.py"
    - "python3 -m pytest src/"
    - "vendor/bin/phpunit"
    - "cd /opt/phpsrc/otic && phpize --clean && phpize && ./configure && NO_INTERACTION=1 make test"

  testphp:
    - sudo phpenmod xdebug
    - vendor/bin/phpunit


  benchphp:
    - sudo phpdismod xdebug
    - vendor/bin/phpunit


  run:
  dev:
    - "echo 'I am executed in dev mode'"
