# Kickstart container config file - see https://gitub.com/infracamp/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "infracamp/kickstart-flavor-base"
command:
  build:
    - "sudo apt-get update"
    - "sudo apt-get install -y pkg-config libzstd1-dev build-essential php7.2-dom php7.2-mbstring php-dev cmake"
    - "sudo rm -rf deps/Unity"
    - "[[ -d 'deps/Unity' ]] || git clone https://github.com/ThrowTheSwitch/Unity.git deps/Unity"
    - "sudo rm -rf build"
    - "sudo rm -rf deps/Unity/build"
    - "mkdir -p deps/Unity/build"
#    - "cmake deps/Unity -Bdeps/Unity/build -DCMAKE_BUILD_TYPE=Release && sudo make -C deps/Unity/build install"

  make:
    - "sudo rm -rf build"
    - "mkdir -p build && cmake . -Bbuild -DCMAKE_BUILD_TYPE=Release -DPHP_BIND=ON -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=dist -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=dist && make -C build"
    - "sudo ldconfig"

  test-c:
    - "make test -C `pwd`/build"

  test-php:
    - 'composer install -d "bindings/php7/"'
    - 'php -dextension="`pwd`/dist/libotic_php.so" ./bindings/php7/vendor/bin/phpunit --testdox `pwd`/bindings/php7/test'

  makeTest:
    - "sudo rm -rf build"
    - "mkdir -p build && cmake . -Bbuild -DCMAKE_BUILD_TYPE=Release -DPHP_BIND=ON -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=dist -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=dist && make -C build"
    - "sudo ldconfig"
#    - "make test -C `pwd`/build"
    - 'composer install -d "bindings/php7/"'
    - 'php -dextension="`pwd`/dist/libotic_php.so" ./bindings/php7/vendor/bin/phpunit --testdox `pwd`/bindings/php7/test'

  run:
  dev:
    - "echo 'I am executed in dev mode'"
