name: build

on:
  push:
    branches:
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: /usr/bin/env ./kickstart.sh :make

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: test
      run: /usr/bin/env ./kickstart.sh :makeTest
