name: Test and Build OTIC

on:
  push:
    branches:
      - master

jobs:

  test:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: /usr/bin/env ./kickstart.sh :test

    - uses: actions/upload-artifact@master
      with:
          name: x86_64-otic-mod-php
          path: ./phpsrc/otic/modules/otic.so