name: build

on:
  push:
    branches:
    - rev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: echo "Tiny Tim: God bless us ... everybody.\n";
#        run: /usr/bin/env ./kickstart.sh :make

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: test
      run: echo "Hallo World\n";
#      run: /usr/bin/env ./kickstart.sh :test
