name: Test OTIC

on:
  push:
    branches:
      - master

jobs:

  test:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Ls all
      run: ls -lah
    - name: env
      run: env
    - name: run mkdir
      run: mkdir vendor

    - name: Test 
      run: /usr/bin/env ./kickstart.sh :test

    - uses: actions/upload-artifact@master
      with:
          name: x86-64/otic-php-mod
          path: ./phpsrc/otic/modules/otic.so